<?php if ( ! defined( 'ABSPATH' ) ) exit( 'No direct script access allowed' );


return array(
 	// logo 
    'logo_img_et-desktop',
    'retina_logo_img_et-desktop',
    'logo_align_et-desktop',
    'logo_width_et-desktop',
    'logo_box_model_et-desktop',
    'logo_border_et-desktop',
    'logo_border_color_custom_et-desktop',

    // top header 
    'top_header_wide_et-desktop',
    'top_header_height_et-desktop',
    'top_header_fonts_et-desktop',
    'top_header_zoom_et-desktop',
    'top_header_background_et-desktop',
    'top_header_color_et-desktop',
    'top_header_box_model_et-desktop',
    'top_header_border_et-desktop',
    'top_header_border_color_custom_et-desktop',

    // main header 
    'main_header_wide_et-desktop',
    'main_header_height_et-desktop',
    'main_header_fonts_et-desktop',
    'main_header_zoom_et-desktop',
    'main_header_background_et-desktop',
    'main_header_color_et-desktop',
    'main_header_box_model_et-desktop',
    'main_header_border_et-desktop',
    'main_header_border_color_custom_et-desktop',

    // bottom header 
    'bottom_header_wide_et-desktop',
    'bottom_header_height_et-desktop',
    'bottom_header_fonts_et-desktop',
    'bottom_header_zoom_et-desktop',
    'bottom_header_background_et-desktop',
    'bottom_header_color_et-desktop',
    'bottom_header_box_model_et-desktop',
    'bottom_header_border_et-desktop',
    'bottom_header_border_color_custom_et-desktop',

    // overlap 
    'header_overlap_et-desktop',
    'overlap_breadcrumb_padding_et-desktop',

    // vertical header 
    'header_vertical_et-desktop',
    'header_vertical_menu_type_et-desktop',
    'header_vertical_menu_term',
    'header_vertical_menu_content_fonts_et-desktop',
    'header_vertical_logo_img_et-desktop',
    'header_vertical_logo_width_et-desktop',
    'header_vertical_menu_icon_zoom_et-desktop',
    'header_vertical_width_et-desktop',
    'header_vertical_content_zoom_et-desktop',
    'header_vertical_elements_spacing_et-desktop',
    'header_vertical_background_color_et-desktop',
    'header_vertical_color_et-desktop',
    'header_vertical_section1_content',
    'header_vertical_section2_content',
    'header_vertical_section3_content',

    // headers sticky
    'top_header_sticky_et-desktop',
    'main_header_sticky_et-desktop',
    'bottom_header_sticky_et-desktop',
    'header_sticky_type_et-desktop',
    'headers_sticky_animation_et-desktop',
    'headers_sticky_animation_duration_et-desktop',
    'headers_sticky_start_et-desktop',
    'headers_sticky_logo_img_et-desktop',
    'top_header_sticky_height_et-desktop',
    'top_header_sticky_background_et-desktop',
    'top_header_sticky_color_et-desktop',
    'main_header_sticky_height_et-desktop',
    'main_header_sticky_background_et-desktop',
    'main_header_sticky_color_et-desktop',
    'bottom_header_sticky_height_et-desktop',
    'bottom_header_sticky_background_et-desktop',
    'bottom_header_sticky_color_et-desktop',

    // main menu 
    'menu_item_style_et-desktop',
    'main_menu_term',
    'menu_dropdown_full_width',
    'menu_one_page',
    'menu_arrows',
    'menu_zoom_et-desktop',
    'menu_alignment_et-desktop',
    'menu_item_fonts_et-desktop',
    'menu_item_border_radius_et-desktop',
    'menu_item_color_custom_et-desktop',
    'menu_item_background_color_custom_et-desktop',
    'menu_item_hover_color_custom_et-desktop',
    'menu_item_line_hover_color_custom_et-desktop',
    'menu_item_dots_color_et-desktop',
    'menu_item_dots_color_custom_et-desktop',
    'menu_item_dots_separator_et-desktop',
    'menu_item_background_hover_color_custom_et-desktop',
    'menu_item_box_model_et-desktop',
    'menu_nice_space_et-desktop',
    'menu_item_border_color_custom_et-desktop',
    'menu_item_border_hover_color_custom_et-desktop',

    // secondary menu 
    'menu_2_item_style_et-desktop',
    'main_menu_2_term',
    'menu_2_dropdown_full_width',
    'menu_2_one_page',
    'menu_2_arrows',
    'menu_2_zoom_et-desktop',
    'menu_2_alignment_et-desktop',
    'menu_2_item_fonts_et-desktop',
    'menu_2_item_border_radius_et-desktop',
    'menu_2_item_color_custom_et-desktop',
    'menu_2_item_background_color_custom_et-desktop',
    'menu_2_item_hover_color_custom_et-desktop',
    'menu_2_item_line_hover_color_custom_et-desktop',
    'menu_2_item_dots_color_et-desktop',
    'menu_2_item_dots_color_custom_et-desktop',
    'menu_2_item_dots_separator_et-desktop',
    'menu_2_item_background_hover_color_custom_et-desktop',
    'menu_2_item_box_model_et-desktop',
    'menu_2_nice_space_et-desktop',
    'menu_2_item_border_color_custom_et-desktop',
    'menu_2_item_border_hover_color_custom_et-desktop',
    'menu_dropdown_zoom_et-desktop',
    'menu_dropdown_fonts_et-desktop',
    'menu_dropdown_background_custom_et-desktop',
    'menu_dropdown_color_et-desktop',
    'menu_dropdown_box_model_et-desktop',
    'menu_dropdown_border_et-desktop',
    'menu_dropdown_border_color_custom_et-desktop',

    // all departments 
    'secondary_menu_visibility',
    'secondary_menu_home',
    'all_departments_text',
    'secondary_menu_term',
    'secondary_menu_more_items_link',
    'secondary_menu_more_items_link_after',
	'secondary_menu_less_items_link',
    'secondary_title_fonts_et-desktop',
    'secondary_title_background_color_custom_et-desktop',
    'secondary_title_color_et-desktop',
    'secondary_title_border_radius_et-desktop',
    'secondary_title_box_model_et-desktop',
    'secondary_title_border_et-desktop',
    'secondary_title_border_color_custom_et-desktop',
    'secondary_menu_content_zoom_et-desktop',
    'secondary_menu_content_box_model_et-desktop',
    'secondary_menu_content_border_et-desktop',
    'secondary_menu_content_border_color_custom_et-desktop',

    // mobile menu
    'mobile_menu_type_et-desktop',
    'mobile_menu_icon_et-desktop',
    'mobile_menu_icon_custom_svg_et-desktop',
    'mobile_menu_icon_zoom_et-desktop',
    'mobile_menu_label_et-desktop',
    'mobile_menu_text',
    'mobile_menu_item_click_et-desktop',
    'mobile_menu_content',
    'mobile_menu_2',
    'mobile_menu_2_categories_hide_empty',
    'mobile_menu_2_categories_primary',
    'mobile_menu_term',
    'mobile_menu_one_page',
    'mobile_menu_2_term',
    'mobile_menu_tab_2_text',
    'mobile_menu_logo_type_et-desktop',
    'mobile_menu_logo_width_et-desktop',
    'mobile_menu_content_alignment_et-desktop',
    'mobile_menu_box_model_et-desktop',
    'mobile_menu_border_et-desktop',
    'mobile_menu_border_color_custom_et-desktop',
    'mobile_menu_content_fonts_et-desktop',
    'mobile_menu_zoom_dropdown_et-desktop',
    'mobile_menu_zoom_popup_et-desktop',
    'mobile_menu_overlay_et-desktop',
    'mobile_menu_color2_et-desktop',
    'mobile_menu_max_height_et-desktop',
    'mobile_menu_background_color_et-desktop',
    'mobile_menu_color_et-desktop',
    'mobile_menu_content_box_model_et-desktop',
    'mobile_menu_content_border_et-desktop',
    'mobile_menu_content_border_color_custom_et-desktop',

    // cart 
    'cart_style_et-desktop',
    'cart_icon_et-desktop',
    'cart_icon_custom_svg_et-desktop',
    'cart_icon_zoom_et-desktop',
    'cart_quantity_proportions_et-desktop',
    'cart_label_et-desktop',
    'cart_label_custom',
    'cart_total_et-desktop',
    'cart_content_type_et-desktop',

    'cart_content_type_et-mobile',
    'cart_content_position_et-desktop',
    'cart_content_position_et-mobile',

    'mini-cart-items-count',
    'cart_link_to',
    'cart_custom_url',
    'cart_content_quantity_input_et-desktop',
	'cart_content_quantity_input_et-mobile',
    'cart_content_linked_products_et-desktop',
	'cart_content_linked_products_et-mobile',
    'cart_content_linked_products_type_et-desktop',
    'cart_content_view_cart_button_et-desktop',
    'cart_quantity_et-desktop',
    'cart_quantity_position_et-desktop',
    'cart_quantity_size_et-desktop',
    'cart_quantity_active_background_custom_et-desktop',
    'cart_quantity_active_color_et-desktop',
    'cart_content_alignment_et-desktop',
    'cart_background_et-desktop',
    'cart_background_custom_et-desktop',
    'cart_overlay_background_custom_et-desktop',
    'cart_color_et-desktop',
    'cart_border_radius_et-desktop',
    'cart_box_model_et-desktop',
    'cart_border_et-desktop',
    'cart_border_color_custom_et-desktop',
    'cart_zoom_et-desktop',
    'cart_dropdown_position_et-desktop',
    'cart_dropdown_position_custom_et-desktop',
    'cart_dropdown_background_custom_et-desktop',
    'cart_dropdown_color_et-desktop',
    'cart_content_position_et-desktop',
    'cart_content_box_model_et-desktop',
    'cart_content_border_et-desktop',
    'cart_content_border_color_custom_et-desktop',
    'cart_footer_content_et-desktop',
    'cart_footer_background_custom_et-desktop',
    'cart_footer_color_et-desktop',

    // Header account options
    'account_style_et-desktop',
    'account_icon_et-desktop',
    'account_icon_custom_svg_et-desktop',
    'account_icon_custom_svg_et-mobile',
    'account_icon_zoom_et-desktop',
    'account_content_type_et-desktop',
    'account_content_type_et-mobile',
    'account_menu_term',
    'account_content_position_et-desktop',
    'account_content_position_et-mobile',

    'account_label_et-desktop',
    'account_label_username',
    'account_text',
    'account_logged_in_text',
    'account_content_alignment_et-desktop',
    'account_background_et-desktop',
    'account_background_custom_et-desktop',
    'account_color_et-desktop',
    'account_border_radius_et-desktop',
    'account_box_model_et-desktop',
    'account_border_et-desktop',
    'account_border_color_custom_et-desktop',
    'account_zoom_et-desktop',
    'account_dropdown_position_et-desktop',
    'account_dropdown_position_custom_et-desktop',
    'account_dropdown_background_custom_et-desktop',
    'account_dropdown_color_et-desktop',
    'account_content_box_model_et-desktop',
    'account_content_border_et-desktop',
    'account_content_border_color_custom_et-desktop',

    // // header_widget1
    'header_widget1',
    'header_widget2',
    'header_banner_position',

    // section html_blocks
    'html_block1',
    'html_block1_sections',
    'html_block1_section',
    'html_block2',
    'html_block2_sections',
    'html_block2_section',
    'html_block3',
    'html_block3_sections',
    'html_block3_section',
	'html_block4',
	'html_block4_sections',
	'html_block4_section',
	'html_block5',
	'html_block5_sections',
	'html_block5_section',

    // section promo_text
    'promo_text_package',
    'promo_text_autoplay_et-desktop',
    'promo_text_speed_et-desktop',
    'promo_text_delay_et-desktop',
    'promo_text_navigation_et-desktop',
	'promo_text_navigation_static_et-desktop',
    'promo_text_close_button_et-desktop',
    'promo_text_close_button_action_et-desktop',
    'promo_text_height_et-desktop',
    'promo_text_background_custom_et-desktop',
    'promo_text_color_et-desktop',

    // section button
    'button_text_et-desktop',
    'button_link_et-desktop',
    'button_custom_link_et-desktop',
    'button_fonts_et-desktop',
    'button_zoom_et-desktop',
    'button_content_align_et-desktop',
    'button_background_custom_et-desktop',
    'button_color_et-desktop',
    'button_background_hover_custom_et-desktop',
    'button_hover_color_et-desktop',
    'button_border_radius_et-desktop',
    'button_box_model_et-desktop',
    'button_border_et-desktop',
    'button_border_color_custom_et-desktop',
    'button_target_et-desktop',
    'button_no_follow_et-desktop',

    // section newsletter
    'newsletter_shown_on_et-desktop',
    'newsletter_delay_et-desktop',
    'newsletter_icon_et-desktop',
    'newsletter_label_show_et-desktop',
    'newsletter_label_et-desktop',
    'newsletter_title_et-desktop',
    'newsletter_content_et-desktop',
    'newsletter_sections_et-desktop',
    'newsletter_section_et-desktop',
    'newsletter_content_alignment_et-desktop',
    'newsletter_content_width_height_et-desktop',
    'newsletter_content_width_height_custom_et-desktop',
    'newsletter_background_et-desktop',
    'newsletter_color_et-desktop',
    'newsletter_box_model_et-desktop',
    'newsletter_border_et-desktop',
    'newsletter_border_color_custom_et-desktop',

    // section contacts
    'contacts_icon_et-desktop',
    'contacts_direction_et-desktop',
    'contacts_package_et-desktop',
    'contacts_separator_et-desktop',
    'contacts_separator_type_et-desktop',
    'contacts_alignment_et-desktop',
    'contact_box_model_et-desktop',
    'contact_border_et-desktop',
    'contact_border_color_custom_et-desktop',

    // section header_socials
    'header_socials_type_et-desktop',
    'header_socials_package_et-desktop',
    'header_socials_direction_et-desktop',
    'header_socials_content_alignment_et-desktop',
    'header_socials_elements_zoom_et-desktop',
    'header_socials_elements_spacing_et-desktop',
    'header_socials_target_et-desktop',
    'header_socials_no_follow_et-desktop',

    // section search
    'search_type_et-desktop',
    'search_icon_et-desktop',
//    'search_icon_et-mobile',
    'search_icon_custom_et-desktop',
//    'search_icon_custom_et-mobile',
	'search_icon_custom_et-desktop',
    'search_label_et-desktop',
    'search_label_et-mobile',
    'search_label_custom_et-desktop',
    'search_ajax_et-desktop',
    'search_ajax_min_symbols_et-desktop',
    'search_ajax_posts_per_page',
    'search_by_sku_et-desktop',
    'search_category_et-desktop',
	'search_product_variation_et-desktop',
	'search_product_hide_variation_parent_et-desktop',
    'search_results_et-desktop',
    'search_all_categories_text_et-desktop',
    'search_page_sidebar_et-desktop',
    'search_results_content_et-desktop',
    'search_placeholder_et-desktop',
//	'search_trending_et-desktop',
	'search_tags_et-desktop',
    'search_extra_content_et-desktop',
    'search_categories_et-desktop',
    'search_html_block_et-desktop',
    'search_staticblock',
    'search_icon_zoom_et-desktop',
    'search_content_alignment_et-desktop',
    'search_width_et-desktop',
    'search_height_et-desktop',
    'search_border_radius_et-desktop',
    'search_color_et-desktop',
    'search_background_color_custom_et-desktop',
    'search_button_background_custom_et-desktop',
    'search_button_color_et-desktop',
	'search_category_fancy_select_et-desktop',
    'search_category_select_color_scheme_et-desktop',
    'search_input_box_model_et-desktop',
    'search_input_border_et-desktop',
    'search_input_border_color_custom_et-desktop',
    'search_icon_box_model_et-desktop',
    'search_icon_border_et-desktop',
    'search_icon_border_color_custom_et-desktop',
    'search_zoom_et-desktop',
    'search_content_position_et-desktop',
    'search_content_position_custom_et-desktop',
    'search_content_box_model_et-desktop',
    'search_content_border_et-desktop',
    'search_content_border_color_custom_et-desktop',

    // section wishlist
    'wishlist_style_et-desktop',
    'wishlist_icon_et-desktop',
    'wishlist_icon_custom_svg_et-desktop',
    'wishlist_icon_zoom_et-desktop',
    'wishlist_quantity_proportions_et-desktop',
    'wishlist_label_et-desktop',
    'wishlist_label_custom_et-desktop',
    'wishlist_content_type_et-desktop',

    'wishlist_content_type_et-mobile',
    'wishlist_content_position_et-desktop',
    'wishlist_content_position_et-mobile',

    'wishlist_link_to',
    'wishlist_custom_url',
    'mini-wishlist-items-count',
    'wishlist_quantity_et-desktop',
    'wishlist_quantity_position_et-desktop',
    'wishlist_quantity_size_et-desktop',
    'wishlist_quantity_active_background_custom_et-desktop',
    'wishlist_quantity_active_color_et-desktop',
    'wishlist_content_alignment_et-desktop',
    'wishlist_background_et-desktop',
    'wishlist_background_custom_et-desktop',
    'wishlist_color_et-desktop',
    'wishlist_border_radius_et-desktop',
    'wishlist_box_model_et-desktop',
    'wishlist_border_et-desktop',
    'wishlist_border_color_custom_et-desktop',
    'wishlist_zoom_et-desktop',
    'wishlist_dropdown_position_et-desktop',
    'wishlist_dropdown_position_custom_et-desktop',
    'wishlist_dropdown_background_custom_et-desktop',
    'wishlist_dropdown_background_custom_et-desktop',
    'wishlist_content_position_et-desktop',
    'wishlist_content_box_model_et-desktop',
    'wishlist_content_border_et-desktop',
    'wishlist_content_border_color_custom_et-desktop',

    // compare
    'compare_style_et-desktop',
    'compare_icon_custom_svg_et-desktop',
    'compare_icon_zoom_et-desktop',
    'compare_icon_zoom_et-mobile',
    'compare_label_et-desktop',
    'compare_label_et-mobile',
    'compare_label_custom_et-desktop',
    'compare_content_type_et-desktop',
    'compare_content_type_et-mobile',
    'compare_link_to',
    'compare_custom_url',
    'mini-compare-items-count',
    'compare_quantity_et-desktop',
    'compare_quantity_position_et-desktop',
    'compare_quantity_size_et-desktop',
    'compare_quantity_proportions_et-desktop',
    'compare_quantity_active_background_custom_et-desktop',
    'compare_quantity_active_color_et-desktop',
    'compare_content_alignment_et-desktop',
    'compare_content_alignment_et-mobile',
    'compare_background_et-desktop',
    'compare_background_custom_et-desktop',
    'compare_color_et-desktop',
    'compare_overlay_background_custom_et-desktop',
    'compare_border_radius_et-desktop',
    'compare_box_model_et-desktop',
    'compare_box_model_et-mobile',
    'compare_border_et-desktop',
    'compare_border_color_custom_et-desktop',
    'compare_zoom_et-desktop',
    'compare_zoom_et-mobile',
    'compare_dropdown_position_et-desktop',
    'compare_dropdown_position_custom_et-desktop',
    'compare_dropdown_background_custom_et-desktop',
    'compare_dropdown_color_et-desktop',
    'compare_content_position_et-desktop',
    'compare_content_position_et-mobile',
    'compare_content_box_model_et-desktop',
    'compare_content_border_et-desktop',
    'compare_content_border_color_custom_et-desktop',

    //////////////////////////////////// 
    // mobile 
    //////////////////////////////////// 
    'logo_align_et-mobile',
    'logo_width_et-mobile',
    'logo_box_model_et-mobile',

    'top_header_height_et-mobile',
    'top_header_zoom_et-mobile',
    'top_header_background_et-mobile',
    'top_header_color_et-mobile',

    'main_header_height_et-mobile',
    'main_header_zoom_et-mobile',
    'main_header_background_et-mobile',
    'main_header_color_et-mobile',

    'bottom_header_height_et-mobile',
    'bottom_header_zoom_et-mobile',
    'bottom_header_background_et-mobile',
    'bottom_header_color_et-mobile',

    'top_header_sticky_et-mobile',
    'main_header_sticky_et-mobile',
    'bottom_header_sticky_et-mobile',

    'top_header_sticky_height_et-mobile',
    'main_header_sticky_height_et-mobile',
    'bottom_header_sticky_height_et-mobile',

    'top_header_sticky_background_et-mobile',
    'top_header_sticky_color_et-mobile',

    'main_header_sticky_background_et-mobile',
    'main_header_sticky_color_et-mobile',

    'bottom_header_sticky_background_et-mobile',
    'bottom_header_sticky_color_et-mobile',

    // overlap 
    'header_overlap_et-mobile',
    'overlap_breadcrumb_padding_et-mobile',

    'menu_zoom_et-mobile',
    'menu_2_zoom_et-mobile',

    'mobile_menu_icon_zoom_et-mobile',
    'mobile_menu_box_model_et-mobile',

    'mobile_menu_content_alignment_et-mobile',

    'cart_icon_zoom_et-mobile',
    'cart_label_et-mobile',
    'cart_total_et-mobile',
    'cart_content_alignment_et-mobile',
    'cart_box_model_et-mobile',
    'cart_zoom_et-mobile',

    'account_icon_zoom_et-mobile',
    'account_icon_et-mobile',
    'account_label_et-mobile',
    'account_content_alignment_et-mobile',
    'account_box_model_et-mobile',

    'button_content_align_et-mobile',

    'header_socials_content_alignment_et-mobile',
    'header_socials_elements_zoom_et-mobile',
    'header_socials_elements_spacing_et-mobile',

    'search_type_et-mobile',
    'search_icon_zoom_et-mobile',
    'search_content_alignment_et-mobile',
    'search_width_et-mobile',
    'search_height_et-mobile',
    'search_border_radius_et-mobile',
    'search_input_box_model_et-mobile',
    'search_icon_box_model_et-mobile',
    'search_zoom_et-mobile',
    'search_content_box_model_et-mobile',

    'wishlist_icon_zoom_et-mobile',
    'wishlist_label_et-mobile',
    'wishlist_content_alignment_et-mobile',
    'wishlist_box_model_et-mobile',
    'wishlist_zoom_et-mobile',
);