<?php if ( ! defined('ABSPATH' ) ) exit('No direct script access allowed' );


return array(

	// button
	'single_product_button_text_et-desktop',
	'single_product_button_link_et-desktop',
	'single_product_button_custom_link_et-desktop',
	'single_product_button_fonts_et-desktop',
	'single_product_button_zoom_et-desktop',
	'single_product_button_content_align_et-desktop',
	'single_product_button_background_custom_et-desktop',
	'single_product_button_color_et-desktop',
	'single_product_button_background_hover_custom_et-desktop',
	'single_product_button_hover_color_et-desktop',
	'single_product_button_border_radius_et-desktop',
	'single_product_button_box_model_et-desktop',
	'single_product_button_border_et-desktop',
	'single_product_button_border_color_custom_et-desktop',
	'single_product_button_target_et-desktop',
	'single_product_button_no_follow_et-desktop',

	// html blocks
	'single_product_html_block1',
	'single_product_html_block1_sections',
	'single_product_html_block1_section',
	'single_product_html_block2',
	'single_product_html_block2_sections',
	'single_product_html_block2_section',
	'single_product_html_block3',
	'single_product_html_block3_sections',
	'single_product_html_block3_section',
	'single_product_html_block4',
	'single_product_html_block4_sections',
	'single_product_html_block4_section',
	'single_product_html_block5',
	'single_product_html_block5_sections',
	'single_product_html_block5_section',

	// breadcrumbs 
	'product_breadcrumbs_mode_et-desktop',
	'product_breadcrumbs_style_et-desktop',
	'product_breadcrumbs_return_to_previous_et-desktop',
	'product_breadcrumbs_product_title_et-desktop',
	'product_breadcrumbs_product_title_duplicated_et-desktop',
	'product_breadcrumbs_type_et-desktop',
	'product_breadcrumbs_width_et-desktop',
	'product_breadcrumbs_zoom_et-desktop',
	'product_breadcrumbs_fonts_et-desktop',
	'product_breadcrumbs_return_to_previous_fonts_et-desktop',
	'product_breadcrumbs_product_title_fonts_et-desktop',
	'product_breadcrumbs_product_title_sizes_et-desktop',
	'product_breadcrumbs_product_title_size_proportion_et-desktop',
	'product_breadcrumbs_product_title_line_height_et-desktop',
	'product_breadcrumbs_background_et-desktop',
	'product_breadcrumbs_color_et-desktop',
	'product_breadcrumbs_box_model_et-desktop',
	'product_breadcrumbs_border_et-desktop',
	'product_breadcrumbs_border_color_custom_et-desktop',

	// countdown
    'single_countdown_type',
	'single_countdown_title',

	// form.cart
	'product_quantity_style_et-desktop',
	'product_add_to_cart_fonts_et-desktop',
	'product_add_to_cart_size_et-desktop',
	'product_add_to_cart_min_width_et-desktop',
	'product_add_to_cart_min_height_et-desktop',
	'product_add_to_cart_radius_et-desktop',
	'product_cart_background_custom_et-desktop',
	'product_cart_color_et-desktop',
	'product_cart_background_custom_hover_et-desktop',
	'product_cart_color_hover_et-desktop',
	'product_cart_buy_now_color_et-desktop',
	'product_cart_buy_now_background_color_et-desktop',
	'product_cart_buy_now_color_hover_et-desktop',
	'product_cart_buy_now_background_color_hover_et-desktop',
	'product_cart_form_box_model_et-desktop',
	'product_cart_form_border_et-desktop',
	'product_cart_form_border_color_custom_et-desktop',
	'stretch_add_to_cart_et-desktop',
	'ajax_add_to_cart',
	'sticky_add_to_cart_et-desktop',
	'sticky_added_to_cart_message',
	'product_cart_form_direction_et-desktop',
    'product_quantity_select_ranges',

	// gallery 
	'product_gallery_type_et-desktop',
	'product_gallery_zoom_et-desktop',
	'product_gallery_lightbox_et-desktop',
	'product_gallery_thumbnails_et-desktop',
	'product_gallery_width_et-desktop',
	'product_thumbnails_columns_et-desktop',
	'product_gallery_spacing_et-desktop',
	'product_gallery_arrow_size',
	'product_gallery_lightbox_background_color_custom',
	'product_gallery_box_model_et-desktop',
	'product_gallery_border_et-desktop',
	'product_gallery_border_color_custom_et-desktop',

	// variations gallery 
	'enable_variation_gallery',

	// product meta 
	'product_meta_content',
	'product_meta_align_et-desktop',
	'product_meta_direction_et-desktop',
	'product_meta_box_model_et-desktop',
	'product_meta_border_et-desktop',
	'product_meta_border_color_custom_et-desktop',

	// product navigation
	'product_navigation_et-desktop',	

	// product price 
	'product_price_align_et-desktop',
	'product_price_proportion_et-desktop',
	'product_price_color_custom_et-desktop',
	'product_price_sale_color_custom_et-desktop',
	'product_price_box_model_et-desktop',
	'product_price_border_et-desktop',
	'product_price_border_color_custom_et-desktop',

	// product rating
	'product_rating_align_et-desktop',
	'product_rating_box_model_et-desktop',
	'product_rating_border_et-desktop',
	'product_rating_border_color_custom_et-desktop',

	// product sale label
	'product_sale_label_type_et-desktop',
	'product_sale_label_percentage_et-desktop',
  	'product_sale_label_text_et-desktop',
	'product_sale_label_position_et-desktop',
	'product_sale_label_position_asix_et-desktop',
	'product_sale_label_content_zoom_et-desktop',
	'product_sale_label_zoom_et-desktop',
	'product_sale_label_border_radius_et-desktop',
	'product_sale_label_background_custom_et-desktop',
	'product_sale_label_color_et-desktop',

	// product sharing 
	'product_sharing_type_et-desktop',
	'product_sharing_package_et-desktop',
	'product_socials_label_et-desktop',
	'product_sharing_content_alignment_et-desktop',
	'product_sharing_label_proportion_et-desktop',
	'product_sharing_elements_zoom_et-desktop',
	'product_sharing_title_color_et-desktop',
	'product_sharing_title_color_custom_et-desktop',
	'product_sharing_color_custom_et-desktop',
	'product_sharing_elements_spacing_et-desktop',
	'product_sharing_box_model_et-desktop',
	'product_sharing_border_et-desktop',
	'product_sharing_border_color_custom_et-desktop',
	'product_sharing_target_et-desktop',
	'product_sharing_no_follow_et-desktop',

	// product short navigation 
	'product_short_description_align_et-desktop',
	'product_short_description_box_model_et-desktop',
	'product_short_description_border_et-desktop',
	'product_short_description_border_color_custom_et-desktop',

	// product size guide
	'product_size_guide_icon_et-desktop',
	'product_size_guide_icon_custom_et-desktop',
	'product_size_guide_label_show_et-desktop',
	'product_size_guide_label_et-desktop',
	'product_size_guide_label_proportion_et-desktop',
	'product_size_guide_type_et-desktop',
	'product_size_guide_content_alignment_et-desktop',
	'product_size_guide_title_et-desktop',
	'product_size_guide_img_et-desktop',
	'product_size_guide_file_et-desktop',
	'product_size_guide_sections_et-desktop',
	'product_size_guide_section_et-desktop',
	'product_size_guide_align_et-desktop',
	'product_size_guide_space_between_et-mobile',
	'product_size_guide_content_width_height_et-desktop',
	'product_size_guide_content_width_height_custom_et-desktop',
	'product_size_guide_popup_box_model_et-desktop',
	'product_size_guide_popup_border_et-desktop',
	'product_size_guide_popup_border_color_custom_et-desktop',

	// product tabs
	'product_tabs_type_et-desktop',
	'product_tabs_style_et-desktop',
	'product_tabs_sortable',
	'product_first_tab_opened_et-desktop',
    'product_tabs_opened_et-desktop',
	'product_reviews_in_two_columns_et-desktop',
	'product_reviews_et-desktop',
	'product_reviews_collapsed_et-mobile',
	'product_tabs_navigation_align_et-desktop',
	'product_tabs_navigation_fonts_et-desktop',
	'product_tabs_navigation_background_et-desktop',
	'product_tabs_navigation_background_custom_et-desktop',
	'product_tabs_navigation_color_custom_et-desktop',
	'product_tabs_navigation_active_background_custom_et-desktop',
	'product_tabs_navigation_active_color_custom_et-desktop',
	'product_tabs_navigation_size_et-desktop',
	'product_tabs_scroll_et-desktop',
	'product_tabs_height_et-desktop',
	'product_tabs_vertical_proportion_et-desktop',
	'product_tabs_navigation_spacing_et-desktop',
	'product_tabs_accordion_navigation_spacing_et-desktop',
	'product_tabs_box_model_et-desktop',
	'product_tabs_border_et-desktop',
	'product_tabs_border_color_custom_et-desktop',
	'product_tabs_custom_tab_01_title_et-desktop',
	'product_tabs_custom_tab_01_content_et-desktop',
	'product_tabs_custom_tab_01_sections_et-desktop',
	'product_tabs_custom_tab_01_section_et-desktop',
	'product_tabs_custom_tab_02_title_et-desktop',
	'product_tabs_custom_tab_02_content_et-desktop',
	'product_tabs_custom_tab_02_sections_et-desktop',
	'product_tabs_custom_tab_02_section_et-desktop',
	
	// product title
	'product_title_align_et-desktop',
	'product_title_proportion_et-desktop',
	'product_title_fonts_et-desktop',
	'product_title_box_model_et-desktop',
	'product_title_border_et-desktop',
	'product_title_border_color_custom_et-desktop',

	// product wishlist
	'product_wishlist_icon_et-desktop',
	'product_wishlist_icon_custom',
//	'product_wishlist_label_type_et-desktop',
	'product_wishlist_label_add_to_wishlist',
	'product_wishlist_label_browse_wishlist',
	'product_wishlist_align_et-desktop',
	'product_wishlist_proportion_et-desktop',
	'product_wishlist_background_custom_et-desktop',
	'product_wishlist_color_et-desktop',
	'product_wishlist_background_hover_custom_et-desktop',
	'product_wishlist_hover_color_et-desktop',
	'product_wishlist_border_radius_et-desktop',
	'product_wishlist_box_model_et-desktop',
	'product_wishlist_border_et-desktop',
	'product_wishlist_border_color_custom_et-desktop',

	// product compare
    'product_compare_icon_et-desktop',
    'product_compare_icon_custom_svg_et-desktop',
    'product_compare_label_add_to_compare',
    'product_compare_label_browse_compare',
    'product_compare_tooltip',
    'product_compare_only_icon',
    'product_compare_redirect_on_remove',
	'product_compare_align_et-desktop',
	'product_compare_proportion_et-desktop',
	'product_compare_background_custom_et-desktop',
	'product_compare_color_et-desktop',
	'product_compare_background_hover_custom_et-desktop',
	'product_compare_hover_color_et-desktop',
	'product_compare_border_radius_et-desktop',
	'product_compare_box_model_et-desktop',
	'product_compare_border_et-desktop',
	'product_compare_border_color_custom_et-desktop',

	// products related 
	'products_related_type_et-desktop',
	'products_related_per_view_et-desktop',
	'products_related_per_view_et-mobile',
	'products_related_limit_et-desktop',
	'products_related_out_of_stock_et-desktop',
	'products_related_cols_gap_et-desktop',
	'products_related_rows_gap_et-desktop',
	'products_related_arrow_size',
	'products_related_title_align_et-desktop',
	'products_related_title_sizes_et-desktop',
	'products_related_title_size_proportion_et-desktop',
	'products_related_title_line_height_et-desktop',
	'products_related_title_margin_bottom_et-desktop',
	'products_related_sale_label_et-desktop',
	'products_related_view_et-desktop',
	'products_related_box_model_et-desktop',
	'products_related_border_et-desktop',
	'products_related_border_color_custom_et-desktop',
	'products_related_product_view_et-desktop',
	'products_related_product_view_color_et-desktop',
	'products_related_product_img_hover_et-desktop',

	// products upsell 
	'products_upsell_type_et-desktop',
	'products_upsell_per_view_et-desktop',
	'products_upsell_per_view_et-mobile',
	'products_upsell_limit_et-desktop',
	'products_upsell_out_of_stock_et-desktop',
	'products_upsell_cols_gap_et-desktop',
	'products_upsell_rows_gap_et-desktop',
	'products_upsell_arrow_size',
	'products_upsell_title_align_et-desktop',
	'products_upsell_title_sizes_et-desktop',
	'products_upsell_title_size_proportion_et-desktop',
	'products_upsell_title_line_height_et-desktop',
	'products_upsell_title_margin_bottom_et-desktop',
	'products_upsells_sale_label_et-desktop',
	'products_upsell_view_et-desktop',
	'products_upsell_box_model_et-desktop',
	'products_upsell_border_et-desktop',
	'products_upsell_border_color_custom_et-desktop',
	'products_upsell_product_view_et-desktop',
	'products_upsell_product_view_color_et-desktop',
	'products_upsell_product_img_hover_et-desktop',
	
	// products cross_sell
	'products_cross_sell_type_et-desktop',
	'products_cross_sell_per_view_et-desktop',
	'products_cross_sell_per_view_et-mobile',
	'products_cross_sell_limit_et-desktop',
	'products_cross_sell_out_of_stock_et-desktop',
	'products_cross_sell_cols_gap_et-desktop',
	'products_cross_sell_rows_gap_et-desktop',
	'products_cross_sell_arrow_size',
	'products_cross_sell_title_align_et-desktop',
	'products_cross_sell_title_sizes_et-desktop',
	'products_cross_sell_title_size_proportion_et-desktop',
	'products_cross_sell_title_line_height_et-desktop',
	'products_cross_sell_title_margin_bottom_et-desktop',
	'products_cross_sells_sale_label_et-desktop',
	'products_cross_sell_view_et-desktop',
	'products_cross_sell_box_model_et-desktop',
	'products_cross_sell_border_et-desktop',
	'products_cross_sell_border_color_custom_et-desktop',
	'products_cross_sells_product_view_et-desktop',
	'products_cross_sells_product_view_color_et-desktop',
	'products_cross_sells_product_img_hover_et-desktop',

    'single_product_bought_together_products_title',
    'single_product_bought_together_redirect',

	// single product layout 
	'single_product_sidebar_mode_et-desktop',
	'single_product_sidebar_et-desktop',
	'single_product_sidebar_sticky_et-desktop',
	'single_product_widget_area_1_et-desktop',
	'single_product_widget_area_1_widget_toggle_et-desktop',
	'single_product_widget_area_1_widget_toggle_actions_et-desktop',
	'single_product_widget_area_1_widget_scroll_et-desktop',
	'single_product_widget_area_1_title_fonts_et-desktop',
	'single_product_widget_area_1_title_size_proportion_et-desktop',
	'single_product_widget_area_1_widget_spacing_et-desktop',
	'single_product_widget_area_1_widget_scroll_height_et-desktop',
	'single_product_sidebar_box_model_et-desktop',
	'single_product_sidebar_border_et-desktop',
	'single_product_sidebar_border_color_custom_et-desktop',
	'single_product_widget_area_1_box_model_et-desktop',
	'single_product_widget_area_1_border_et-desktop',
	'single_product_widget_area_1_border_color_custom_et-desktop',

);